channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.3.1
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.1
  - scipy==1.13.0
name: mlflow-env
